Presupuesto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login',login, {'template_name':'index.html'},name="login"), 
    url(r'^',include('apps.propiedades.urls',namespace="propiedades")),
    url(r'^',include('apps.proyectos.urls',namespace="proyectos")),
    url(r'^logout/',logout_then_login, name="logout"),
]

apps/propiedades/urls.py
from __future__ import absolute_import
from django.conf.urls import url
from django.contrib.auth.decorators import login_required


from apps.propiedades.views import Sector_listar,Sector_crear,Sector_actualizar,Sector_eliminar,api_sector
from apps.propiedades.views import Fuente_listar,Fuente_crear,Fuente_actualizar,Fuente_eliminar,api_fuente
from apps.propiedades.views import Sit_listar,Sit_crear,Sit_actualizar,Sit_eliminar
from apps.propiedades.views import Unidad_ejecutora_listar,Unidad_ejecutora_crear,Unidad_ejecutora_actualizar,Unidad_ejecutora_eliminar


urlpatterns = [
    
    url(r'^sector/listar$', login_required(Sector_listar.as_view()),name='sector_listar'),
    url(r'^sector/nuevo$', login_required( Sector_crear.as_view()),name='sector_crear'),
    url(r'^sector/edit/(?P<pk>\d+)/$',login_required( Sector_actualizar.as_view()),name='sector_actualizar'),
    url(r'^sector/delete/(?P<pk>\d+)/$', login_required(Sector_eliminar.as_view()),name='sector_eliminar'),
    url(r'^sector/api$', api_sector,name='api'),

    url(r'^fuente/listar$', login_required(Fuente_listar.as_view()),name='fuente_listar'),
    url(r'^fuente/nuevo$', login_required( Fuente_crear.as_view()),name='fuente_crear'),
    url(r'^fuente/edit/(?P<pk>\d+)/$',login_required( Fuente_actualizar.as_view()),name='fuente_actualizar'),
    url(r'^fuente/delete/(?P<pk>\d+)/$', login_required(Fuente_eliminar.as_view()),name='fuente_eliminar'),
    url(r'^fuente/api$', api_fuente,name='api2'),

    url(r'^sit/listar$', login_required(Sit_listar.as_view()),name='sit_listar'),
    url(r'^sit/nuevo$', login_required( Sit_crear.as_view()),name='sit_crear'),
    url(r'^sit/edit/(?P<pk>\d+)/$',login_required( Sit_actualizar.as_view()),name='sit_actualizar'),
    url(r'^sit/delete/(?P<pk>\d+)/$', login_required(Sit_eliminar.as_view()),name='sit_eliminar'),

    url(r'^unidad/listar$', login_required(Unidad_ejecutora_listar.as_view()),name='unidad_ejecutora_listar'),
    url(r'^unidad/nuevo$', login_required( Unidad_ejecutora_crear.as_view()),name='unidad_ejecutora_crear'),
    url(r'^unidad/edit/(?P<pk>\d+)/$',login_required( Unidad_ejecutora_actualizar.as_view()),name='unidad_ejecutora_actualizar'),
    url(r'^unidad/delete/(?P<pk>\d+)/$', login_required(Unidad_ejecutora_eliminar.as_view()),name='unidad_ejecutora_eliminar'),


]

apps/propiedades/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

#modelo para  sectores
class Sector (models.Model):
	codigo_sector = models.CharField(primary_key=True,max_length=50)
	nombre_sector = models.CharField(max_length=300)

	def __unicode__(self):
		return '{}'.format(self.nombre_sector)

class Sector2 (models.Model):
	codigo_sector = models.CharField(max_length=50)
	nombre_sector = models.CharField(max_length=300)

	def __unicode__(self):
		return '{}'.format(self.nombre_sector)


#modelo para unidad ejecutora
class Unidad_ejecutora (models.Model):
	
	nombre_unidad = models.CharField(max_length=200)

	def __unicode__(self):
		return '{}'.format(self.nombre_unidad)

# modelo para fuentes
class Fuente (models.Model):
	
	nombre_fuente = models.CharField(max_length=100)

	def __unicode__(self):
		return '{}'.format(self.nombre_fuente)

#modelo para sits (en el ecxcel es un campo que se dennomina asi)
class Sit (models.Model):
	
	nombre_sit = models.CharField(max_length=10)

	def __unicode__(self):
		return '{}'.format(self.nombre_sit)

apps/propiedades/forms.py
# coding=utf-8
from __future__ import absolute_import
from __future__ import unicode_literals
from django import forms
from apps.propiedades.models import Sector,Fuente,Unidad_ejecutora,Fuente,Sit



class SectorForm(forms.ModelForm):
	class Meta:
		model = Sector
		fields = [	

			'codigo_sector',
			'nombre_sector',		
		]

		labels = {

			'codigo_sector': 'Código del sector',	
			'nombre_sector': 'Nombre del sector',	
		}

		widgets = {
			
			'codigo_sector':forms.TextInput(attrs={'class':'form-control'}),
			'nombre_sector':forms.TextInput(attrs={'class':'form-control'}),
					
		}


class FuenteForm(forms.ModelForm):
	class Meta:
		model = Fuente

		fields = [	
							
			'nombre_fuente',		
		]

		labels = {

			'nombre_fuente': 'Nombre del fuente',	
		}

		widgets = {			
			
			'nombre_fuente':forms.TextInput(attrs={'class':'form-control'}),
					
		}

class SitForm(forms.ModelForm):
	class Meta:
		model = Sit

		fields = [					
		
			'nombre_sit',		
		]

		labels = {

			
			'nombre_sit': 'Nombre del sector',	
		}

		widgets = {
			
			'nombre_sit':forms.TextInput(attrs={'class':'form-control'}),
					
		}


class Unidad_ejecutoraForm(forms.ModelForm):
	class Meta:
		model = Unidad_ejecutora

		fields = [	
				
			'nombre_unidad',			
		]

		labels = {

			'nombre_unidad': 'Nombre de la unidad',	
			
		}

		widgets = {
			
			'nombre_unidad':forms.TextInput(attrs={'class':'form-control'}),
			
					
		}

apps/propiedades/views.py
from __future__ import absolute_import
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from apps.propiedades.models import Sector,Fuente,Unidad_ejecutora,Fuente,Sit
from apps.propiedades.forms import SectorForm,FuenteForm,SitForm,Unidad_ejecutoraForm
from apps.propiedades.Serializers import SectorSerializer,FuenteSerializer,SitSerializer,UnidadSerializer
from django.core.urlresolvers import reverse_lazy
from rest_framework.decorators import api_view
from rest_framework.response import Response
# Create your views here.

class Sector_listar(ListView):
	
	model = Sector
	template_name= 'propiedades/sector_listar.html'

class Sector_crear(CreateView):
	model = Sector
	form_class = SectorForm
	template_name= 'propiedades/sector_crear.html'
	success_url = reverse_lazy('propiedades:sector_listar')

class Sector_actualizar(UpdateView):
	model = Sector
	form_class = SectorForm
	template_name= 'propiedades/sector_crear.html'
	success_url = reverse_lazy('propiedades:sector_listar')

class Sector_eliminar(DeleteView):
	model = Sector
	template_name= 'propiedades/sector_eliminar.html'
	success_url = reverse_lazy('propiedades:sector_listar')



class Fuente_listar(ListView):
	model = Fuente
	template_name= 'propiedades/fuente_listar.html'

class Fuente_crear(CreateView):
	model = Fuente
	form_class = FuenteForm
	template_name= 'propiedades/fuente_crear.html'
	success_url = reverse_lazy('propiedades:fuente_listar')

class Fuente_actualizar(UpdateView):
	model = Fuente
	form_class = FuenteForm
	template_name= 'propiedades/fuente_crear.html'
	success_url = reverse_lazy('propiedades:fuente_listar')

class Fuente_eliminar(DeleteView):
	model = Fuente
	template_name= 'propiedades/fuente_eliminar.html'
	success_url = reverse_lazy('propiedades:fuente_listar')




class Unidad_ejecutora_listar(ListView):
	model = Unidad_ejecutora
	template_name= 'propiedades/unidad_ejecutora_listar.html'

class Unidad_ejecutora_crear(CreateView):
	model = Unidad_ejecutora
	form_class = Unidad_ejecutoraForm
	template_name= 'propiedades/unidad_ejecutora_crear.html'
	success_url = reverse_lazy('propiedades:unidad_ejecutora_listar')

class Unidad_ejecutora_actualizar(UpdateView):
	model = Unidad_ejecutora
	form_class = Unidad_ejecutoraForm
	template_name= 'propiedades/unidad_ejecutora_crear.html'
	success_url = reverse_lazy('propiedades:unidad_ejecutora_listar')

class Unidad_ejecutora_eliminar(DeleteView):
	model = Unidad_ejecutora
	template_name= 'propiedades/unidad_ejecutora_eliminar.html'
	success_url = reverse_lazy('propiedades:unidad_ejecutora_listar')
	




class Sit_listar(ListView):
	model = Sit
	template_name= 'propiedades/sit_listar.html'

class Sit_crear(CreateView):
	model = Sit
	form_class = SitForm
	template_name= 'propiedades/sit_crear.html'
	success_url = reverse_lazy('propiedades:sit_listar')

class Sit_actualizar(UpdateView):
	model = Sit
	form_class = SitForm
	template_name= 'propiedades/sit_crear.html'
	success_url = reverse_lazy('propiedades:sit_listar')

class Sit_eliminar(DeleteView):
	model = Sit
	template_name= 'propiedades/sit_eliminar.html'
	success_url = reverse_lazy('propiedades:sit_listar')
	



@api_view(['POST'])
def api_sector(request):
	cod_sector = request.data["sector_id"]
	nombre_sector = request.data["nombre"]

	

	serializer_class= SectorSerializer
	try:
		if cod_sector == '' and nombre_sector == '':
			sectores = Sector.objects.all()
			many = True
		if nombre_sector=='':
			sectores = Sector.objects.filter(codigo_sector=cod_sector)
			many = True
		if cod_sector=='':
			sectores = Sector.objects.filter(nombre_sector=nombre_sector)
			many = True
		if cod_sector != '' and nombre_sector != '':
			sectores = Sector.objects.filter(nombre_sector=nombre_sector,codigo_sector=cod_sector)
			many = True

		

		response = serializer_class(sectores,many=many)
		
		return Response(response.data)
		

	except Sector.DoesNotExist:
			return Response([{'error': 'sectores no encontrados'}])


@api_view(['POST'])
def api_fuente(request):
	cod_fuente = request.data["id"]
	nombre_fuente = request.data["nombre"]

	

	serializer_class= FuenteSerializer
	try:
		if cod_fuente == '0' and nombre_fuente == '0':
			fuentes = Fuente.objects.all()
			many = True
		if nombre_fuente=='':
			fuentes = Fuente.objects.filter(id=cod_fuente)
			many = True
		if cod_fuente=='':
			fuentes = Fuente.objects.filter(nombre_fuente=nombre_fuente)
			many = True
		if cod_fuente != '' and nombre_fuente != '':
			fuentes = Fuente.objects.filter(nombre_fuente=nombre_fuente,id=cod_fuente)
			many = True

		

		response = serializer_class(fuentes,many=many)
		
		return Response(response.data)
		

	except Fuente.DoesNotExist:
			return Response([{'error': 'fuentes no encontrados'}])
	
	

	

templates/propiedades/fuente_crear.html
{% extends 'base.html' %}

{% block content%}
	<form method="POST">
		{% csrf_token %}
		
		{{form.as_p}}
		

		<button type="submit">Guardar</button>
	</form>
{% endblock %}

templates/propiedades/fuente_eliminar.html
{% extends 'base.html' %}

{% block content%}
	<form method="POST">
		{% csrf_token %}
		<h3>¿Desea eliminar el registro </h3>
		<button class="btm btn-danger" type="submit">si, Eliminar</button>
		<a class="btn btn-default" href="{% url 'propiedades:fuente_listar'%}">Cancelar</a>

	</form>
{% endblock %}

templates/propiedades/fuente_listar.html
{% extends 'base.html' %}

{% block content%}
	
<table class="table table-bordered">
	<thead>
		<tr>
			
			<td>Nombre de fuente</td>
			
		</tr>
	</thead>
	<tbody>	
		{% if object_list %}
		{% for fuente in object_list %}
		<tr>
			<td>{{ fuente.nombre_fuente }}</td>
			
			
			<td>
				<a class="btn btn-primary" href="{% url 'propiedades:fuente_actualizar' fuente.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'propiedades:fuente_eliminar' fuente.id %}">Eliminar</a>
			</td>
			
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de Fuentes</h1>

		{% endif %}
	</tbody>
</table>

<a class="btn btn-primary" href="{% url 'propiedades:fuente_crear'  %}">Crear </a>
{% endblock %}

templates/propiedades/sector_crear.html
{% extends 'base.html' %}

{% block content%}
	<form method="POST">
		{% csrf_token %}
		
		{{form.as_p}}
		

		<button type="submit">Guardar</button>
	</form>
{% endblock %}

templates/propiedades/sector_eliminar.html
{% extends 'base.html' %}

{% block content%}
	<form method="POST">
		{% csrf_token %}
		<h3>¿Desea eliminar el registro </h3>
		<button class="btm btn-danger" type="submit">si, Eliminar</button>
		<a class="btn btn-default" href="{% url 'propiedades:sector_listar'%}">Cancelar</a>

	</form>
{% endblock %}

templates/propiedades/sector_listar.html
{% extends 'base.html' %}

{% block content%}
	
<table class="table table-bordered">
	<thead>
		<tr>
			<td>Codigo sector</td>
			<td>Nombre del sector</td>
			
		</tr>
	</thead>
	<tbody>	
		{% if object_list %}
		{% for sector in object_list %}
		<tr>
			<td>{{ sector.codigo_sector }}</td>
			<td>{{ sector.nombre_sector }}</td>
			
			<td>
				<a class="btn btn-primary" href="{% url 'propiedades:sector_actualizar' sector.codigo_sector %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'propiedades:sector_eliminar' sector.codigo_sector %}">Eliminar</a>
			</td>
			
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de sectores</h1>

		{% endif %}
	</tbody>
</table>
<a class="btn btn-primary" href="{% url 'propiedades:sector_crear'  %}">Crear </a>
{% endblock %}

templates/propiedades/sit_crear.html
{% extends 'base.html' %}

{% block content%}
	<form method="POST">
		{% csrf_token %}
		
		{{form.as_p}}
		

		<button type="submit">Guardar</button>
	</form>
{% endblock %}

templates/propiedades/sit_eliminar.html
{% extends 'base.html' %}

{% block content%}
	<form method="POST">
		{% csrf_token %}
		<h3>¿Desea eliminar el registro </h3>
		<button class="btm btn-danger" type="submit">si, Eliminar</button>
		<a class="btn btn-default" href="{% url 'propiedades:sit_listar'%}">Cancelar</a>

	</form>
{% endblock %}

templates/propiedades/sit_listar.html
{% extends 'base.html' %}

{% block content%}
	
<table class="table table-bordered">
	<thead>
		<tr>
			<td>Nombre Sit</td>
			
			
		</tr>
	</thead>
	<tbody>	
		{% if object_list %}
		{% for sit in object_list %}
		<tr>
			<td>{{ sit.nombre_sit }}</td>
			
			
			<td>
				<a class="btn btn-primary" href="{% url 'propiedades:sit_actualizar' sit.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'propiedades:sit_eliminar' sit.id %}">Eliminar</a>
			</td>
			
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de Sits</h1>

		{% endif %}
	</tbody>
</table>

<a class="btn btn-primary" href="{% url 'propiedades:sit_crear'  %}">Crear </a>
{% endblock %}

templates/propiedades/unidad_ejecutora_crear.html
{% extends 'base.html' %}

{% block content%}
	<form method="POST">
		{% csrf_token %}
		
		{{form.as_p}}
		

		<button type="submit">Guardar</button>
	</form>
{% endblock %}

templates/propiedades/unidad_ejecutora_eliminar.html
{% extends 'base.html' %}

{% block content%}
	<form method="POST">
		{% csrf_token %}
		<h3>¿Desea eliminar el registro </h3>
		<button class="btm btn-danger" type="submit">si, Eliminar</button>
		<a class="btn btn-default" href="{% url 'propiedades:unidad_ejecutora_listar'%}">Cancelar</a>

	</form>
{% endblock %}

templates/propiedades/unidad_ejecutora_listar.html
{% extends 'base.html' %}

{% block content%}
	
<table class="table table-bordered">
	<thead>
		<tr>
			
			<td>Nombre Unidad Ejecutora</td>
			
		</tr>
	</thead>
	<tbody>	
		{% if object_list %}
		{% for unidad in object_list %}
		<tr>
			<td>{{ unidad.nombre_unidad }}</td>
			
			
			<td>
				<a class="btn btn-primary" href="{% url 'propiedades:unidad_ejecutora_actualizar' unidad.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'propiedades:unidad_ejecutora_eliminar' unidad.id %}">Eliminar</a>
			</td>
			
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de Unidades ejecutoras</h1>

		{% endif %}

	</tbody>
</table>

<a class="btn btn-primary" href="{% url 'propiedades:unidad_ejecutora_crear'  %}">Crear </a>
{% endblock %}