Presupuesto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login',login, {'template_name':'index.html'},name="login"), 
    url(r'^',include('apps.propiedades.urls',namespace="propiedades")),
    url(r'^',include('apps.proyectos.urls',namespace="proyectos")),
    url(r'^logout/',logout_then_login, name="logout"),
]

apps/propiedades/urls.py
from __future__ import absolute_import
from django.conf.urls import url
from django.contrib.auth.decorators import login_required


from apps.propiedades.views import Sector_listar,Sector_crear,Sector_actualizar,Sector_eliminar,api_sector
from apps.propiedades.views import Fuente_listar,Fuente_crear,Fuente_actualizar,Fuente_eliminar,api_fuente
from apps.propiedades.views import Sit_listar,Sit_crear,Sit_actualizar,Sit_eliminar
from apps.propiedades.views import Unidad_ejecutora_listar,Unidad_ejecutora_crear,Unidad_ejecutora_actualizar,Unidad_ejecutora_eliminar


urlpatterns = [
    
    url(r'^sector/listar$', login_required(Sector_listar.as_view()),name='sector_listar'),
    url(r'^sector/nuevo$', login_required( Sector_crear.as_view()),name='sector_crear'),
    url(r'^sector/edit/(?P<pk>\d+)/$',login_required( Sector_actualizar.as_view()),name='sector_actualizar'),
    url(r'^sector/delete/(?P<pk>\d+)/$', login_required(Sector_eliminar.as_view()),name='sector_eliminar'),
    url(r'^sector/api$', api_sector,name='api'),

    url(r'^fuente/listar$', login_required(Fuente_listar.as_view()),name='fuente_listar'),
    url(r'^fuente/nuevo$', login_required( Fuente_crear.as_view()),name='fuente_crear'),
    url(r'^fuente/edit/(?P<pk>\d+)/$',login_required( Fuente_actualizar.as_view()),name='fuente_actualizar'),
    url(r'^fuente/delete/(?P<pk>\d+)/$', login_required(Fuente_eliminar.as_view()),name='fuente_eliminar'),
    url(r'^fuente/api$', api_fuente,name='api2'),

    url(r'^sit/listar$', login_required(Sit_listar.as_view()),name='sit_listar'),
    url(r'^sit/nuevo$', login_required( Sit_crear.as_view()),name='sit_crear'),
    url(r'^sit/edit/(?P<pk>\d+)/$',login_required( Sit_actualizar.as_view()),name='sit_actualizar'),
    url(r'^sit/delete/(?P<pk>\d+)/$', login_required(Sit_eliminar.as_view()),name='sit_eliminar'),

    url(r'^unidad/listar$', login_required(Unidad_ejecutora_listar.as_view()),name='unidad_ejecutora_listar'),
    url(r'^unidad/nuevo$', login_required( Unidad_ejecutora_crear.as_view()),name='unidad_ejecutora_crear'),
    url(r'^unidad/edit/(?P<pk>\d+)/$',login_required( Unidad_ejecutora_actualizar.as_view()),name='unidad_ejecutora_actualizar'),
    url(r'^unidad/delete/(?P<pk>\d+)/$', login_required(Unidad_ejecutora_eliminar.as_view()),name='unidad_ejecutora_eliminar'),


]

apps/proyectos/urls.py
from __future__ import absolute_import
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.proyectos.views import Proyecto_listar,Proyecto_crear,Proyecto_actualizar,Proyecto_eliminar,api_proyecto


urlpatterns = [
    
    url(r'^proyecto/listar$', login_required(Proyecto_listar.as_view()),name='proyecto_listar'),
    url(r'^proyecto/nuevo$', login_required( Proyecto_crear.as_view()),name='proyecto_crear'),
    url(r'^proyecto/edit/(?P<pk>\d+)/$',login_required( Proyecto_actualizar.as_view()),name='proyecto_actualizar'),
    url(r'^proyecto/delete/(?P<pk>\d+)/$', login_required(Proyecto_eliminar.as_view()),name='proyecto_eliminar'),
     url(r'^proyecto/api$', api_proyecto,name='api3'),
   
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Document {% endblock %}</title>
</head>
<body>
<div class="container">

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="#">Home</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Propiedades <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{%url 'propiedades:sector_listar' %}">Sectores</a></li>
				                        	<li><a href="{%url 'propiedades:fuente_listar' %}">Fuentes</a></li>
				                        	<li><a href="{%url 'propiedades:sit_listar' %}">Sit</a></li>
				                        	<li><a href="{%url 'propiedades:unidad_ejecutora_listar' %}">Unidad Ejecutora</a></li>
				                        </ul>
		                      		</li>
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">proyectos <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{%url 'proyectos:proyecto_listar' %}">Listar</a></li>
				                        	
				                        </ul>
		                      		</li>
			                       
		                    	</ul>
		                    	<ul class="nav navbar-nav navbar-right">
		                        	<li class="dropdown"><a href="http://monoku.com" onclick="pageTracker._link(this.href); return false;">MONOKU</a>
		                        	</li>
		                        	<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
		                        		<ul class="dropdown-menu" role="menu">
		                          			<li><a href="{% url 'logout'%}">Salir</a></li>
		                        		</ul>
		                      		</li>
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>    

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}


</body>
</html>

templates/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>DNP</title>

        <!-- CSS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="/static/assets2/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/assets2/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="/static/assets2/css/form-elements.css">
        <link rel="stylesheet" href="/static/assets2/css/style.css">
        <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Neucha" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="/static/css/class.css" >



        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="/static/assets/ico/favicon.png">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/static/assets/ico/apple-touch-icon-57-precomposed.png">

       

    </head>

    <body >
        {% csrf_token %}
        <!-- Top menu -->
        <nav class="navbar navbar-inverse navbar-no-bg" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                
                  
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
               

            </div>

        </nav>

        <!-- Top content -->
            <div class="top-content">
                     
                <div class="inner-bg">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-8 col-sm-offset-2 text">
                                    <img src="/static/img/head_logo.png" alt="">
                                       <form  method="post">
                                        {% csrf_token %}
                                     <div class="form-group"></div>
                                    <div class="form-group">
                                        <input type="text"  name="username" placeholder="Usuario"/>
                                    </div>

                                    <div class="form-group"><input type="password"  name="password" placeholder="Contraseña"/>
                                    </div>
                                     <div class="form-group"></div>
                                     <div class="form-group">   <button class="bt-login" type="submit">INGRESAR</button>  

                                        </div>
                                

                                </form>
                                
                            </div>
                           
                               
                            

                        </div>
                        
                    

                    </div>
                    <div class="row">
                        <div class="col-sm-5">
                             
                        </div>
                        <div class="col-sm-5">
                          
                        </div>
                        <div class="col-sm-5">
                            
                        </div>

                       
                        
                    </div>
                </div>
            </div>
            
        </div>


        <!-- Javascript -->
        <script src="/static/assets2/js/jquery-1.11.1.min.js"></script>
        <script src="/static/assets2/bootstrap/js/bootstrap.min.js"></script>
        <script src="/static/assets2/js/jquery.backstretch.min.js"></script>
        <script src="/static/assets2/js/retina-1.1.0.min.js"></script>
        <script src="/static/assets2/js/scripts.js"></script>
        <!--<script src="/static/js/jquery-1.10.2.js"></script>-->
        <script src="/static/js/bootstrap.js"></script>
        <script src="/static/js/jquery.metisMenu.js"></script>
        <script src="/static/js/custom.js"></script>
        <script src="/static/js/jquery.dataTables.min.js"></script>


        
        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->

    </body>

</html>